services:
  init: &init
    image: wlcamargo/spark-dev:3.5.0
    container_name: init
    environment:
      - SPARK_NO_DAEMONIZE=true

  jupyter:
    image: wlcamargo/jupyter-light
    container_name: jupyter
    ports:
      - 8888:8888
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]

  spark-master:
    <<: *init
    container_name: spark-master
    ports:
      - 8080:8080
    expose:
      - 7077
    command: /opt/spark/sbin/start-master.sh
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
  
  spark-worker:
    <<: *init
    container_name: spark-worker
    command: /opt/spark/sbin/start-worker.sh spark://spark-master:7077
    depends_on:
      - spark-master
    deploy:
      replicas: 3
      placement:
        constraints: [node.role == worker]

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "7777:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
